pinecone:
  enabled: true
  api-key: ${PINECONE_API_KEY:}
  index-name: chat-session
  cloud: aws
  region: us-east-1
  create-index: false

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: your_password

  alioss:
    endpointi: oss-cn-beijing.aliyuncs.com
    access-key-id: your_key_id
    access-key-secret: your_key_secret
    bucket-name: your_bucket_name

  redis:
    host: localhost
    port: 6379
    password: your_password

  wechat:
    appid: your_appid
    secret: your_secret